// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0-devel
// 	protoc        v3.13.0
// source: api/coin/v1/coin.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RechargeCoinRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  uint64  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CoinNum float32 `protobuf:"fixed32,2,opt,name=coin_num,json=coinNum,proto3" json:"coin_num,omitempty"`
}

func (x *RechargeCoinRequest) Reset() {
	*x = RechargeCoinRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_coin_v1_coin_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RechargeCoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RechargeCoinRequest) ProtoMessage() {}

func (x *RechargeCoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_coin_v1_coin_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RechargeCoinRequest.ProtoReflect.Descriptor instead.
func (*RechargeCoinRequest) Descriptor() ([]byte, []int) {
	return file_api_coin_v1_coin_proto_rawDescGZIP(), []int{0}
}

func (x *RechargeCoinRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RechargeCoinRequest) GetCoinNum() float32 {
	if x != nil {
		return x.CoinNum
	}
	return 0
}

type RechargeCoinReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrCode int32   `protobuf:"varint,1,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"`
	Balance float32 `protobuf:"fixed32,2,opt,name=balance,proto3" json:"balance,omitempty"`
}

func (x *RechargeCoinReply) Reset() {
	*x = RechargeCoinReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_coin_v1_coin_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RechargeCoinReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RechargeCoinReply) ProtoMessage() {}

func (x *RechargeCoinReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_coin_v1_coin_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RechargeCoinReply.ProtoReflect.Descriptor instead.
func (*RechargeCoinReply) Descriptor() ([]byte, []int) {
	return file_api_coin_v1_coin_proto_rawDescGZIP(), []int{1}
}

func (x *RechargeCoinReply) GetErrCode() int32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

func (x *RechargeCoinReply) GetBalance() float32 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type ConsumeCoinRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  uint64  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CoinNum float32 `protobuf:"fixed32,2,opt,name=coin_num,json=coinNum,proto3" json:"coin_num,omitempty"`
}

func (x *ConsumeCoinRequest) Reset() {
	*x = ConsumeCoinRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_coin_v1_coin_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConsumeCoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeCoinRequest) ProtoMessage() {}

func (x *ConsumeCoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_coin_v1_coin_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeCoinRequest.ProtoReflect.Descriptor instead.
func (*ConsumeCoinRequest) Descriptor() ([]byte, []int) {
	return file_api_coin_v1_coin_proto_rawDescGZIP(), []int{2}
}

func (x *ConsumeCoinRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ConsumeCoinRequest) GetCoinNum() float32 {
	if x != nil {
		return x.CoinNum
	}
	return 0
}

type ConsumeCoinReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrCode int32   `protobuf:"varint,1,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"`
	Balance float32 `protobuf:"fixed32,2,opt,name=balance,proto3" json:"balance,omitempty"`
}

func (x *ConsumeCoinReply) Reset() {
	*x = ConsumeCoinReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_coin_v1_coin_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConsumeCoinReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeCoinReply) ProtoMessage() {}

func (x *ConsumeCoinReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_coin_v1_coin_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeCoinReply.ProtoReflect.Descriptor instead.
func (*ConsumeCoinReply) Descriptor() ([]byte, []int) {
	return file_api_coin_v1_coin_proto_rawDescGZIP(), []int{3}
}

func (x *ConsumeCoinReply) GetErrCode() int32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

func (x *ConsumeCoinReply) GetBalance() float32 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type GetCoinBalanceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId uint64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetCoinBalanceRequest) Reset() {
	*x = GetCoinBalanceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_coin_v1_coin_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCoinBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoinBalanceRequest) ProtoMessage() {}

func (x *GetCoinBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_coin_v1_coin_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoinBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetCoinBalanceRequest) Descriptor() ([]byte, []int) {
	return file_api_coin_v1_coin_proto_rawDescGZIP(), []int{4}
}

func (x *GetCoinBalanceRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetCoinBalanceReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrCode int32   `protobuf:"varint,1,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"`
	Balance float32 `protobuf:"fixed32,2,opt,name=balance,proto3" json:"balance,omitempty"`
}

func (x *GetCoinBalanceReply) Reset() {
	*x = GetCoinBalanceReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_coin_v1_coin_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCoinBalanceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoinBalanceReply) ProtoMessage() {}

func (x *GetCoinBalanceReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_coin_v1_coin_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoinBalanceReply.ProtoReflect.Descriptor instead.
func (*GetCoinBalanceReply) Descriptor() ([]byte, []int) {
	return file_api_coin_v1_coin_proto_rawDescGZIP(), []int{5}
}

func (x *GetCoinBalanceReply) GetErrCode() int32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

func (x *GetCoinBalanceReply) GetBalance() float32 {
	if x != nil {
		return x.Balance
	}
	return 0
}

var File_api_coin_v1_coin_proto protoreflect.FileDescriptor

var file_api_coin_v1_coin_proto_rawDesc = []byte{
	0x0a, 0x16, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x69, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f,
	0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f,
	0x69, 0x6e, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x49, 0x0a, 0x13, 0x52, 0x65, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x43,
	0x6f, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x6f, 0x69, 0x6e, 0x5f, 0x6e, 0x75, 0x6d, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x63, 0x6f, 0x69, 0x6e, 0x4e, 0x75, 0x6d, 0x22, 0x48,
	0x0a, 0x11, 0x52, 0x65, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x43, 0x6f, 0x69, 0x6e, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x22, 0x48, 0x0a, 0x12, 0x43, 0x6f, 0x6e, 0x73,
	0x75, 0x6d, 0x65, 0x43, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x6f, 0x69, 0x6e, 0x5f,
	0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x63, 0x6f, 0x69, 0x6e, 0x4e,
	0x75, 0x6d, 0x22, 0x47, 0x0a, 0x10, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x43, 0x6f, 0x69,
	0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x5f, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x22, 0x30, 0x0a, 0x15, 0x47,
	0x65, 0x74, 0x43, 0x6f, 0x69, 0x6e, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x4a, 0x0a,
	0x13, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x69, 0x6e, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x32, 0xd1, 0x02, 0x0a, 0x04, 0x43, 0x6f,
	0x69, 0x6e, 0x12, 0x67, 0x0a, 0x08, 0x52, 0x65, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x12, 0x20,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x63,
	0x68, 0x61, 0x72, 0x67, 0x65, 0x43, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x52,
	0x65, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x43, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x19, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x13, 0x22, 0x0e, 0x2f, 0x63, 0x6f, 0x69, 0x6e, 0x2f,
	0x72, 0x65, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x3a, 0x01, 0x2a, 0x12, 0x67, 0x0a, 0x0b, 0x43,
	0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x43, 0x6f, 0x69, 0x6e, 0x12, 0x1f, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x63, 0x6f, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65,
	0x43, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x63, 0x6f, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d,
	0x65, 0x43, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x18, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x12, 0x22, 0x0d, 0x2f, 0x63, 0x6f, 0x69, 0x6e, 0x2f, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d,
	0x65, 0x3a, 0x01, 0x2a, 0x12, 0x77, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x69, 0x6e, 0x42,
	0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x69,
	0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x69, 0x6e, 0x42, 0x61, 0x6c, 0x61,
	0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x63, 0x6f, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x69, 0x6e,
	0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1f, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x19, 0x12, 0x17, 0x2f, 0x63, 0x6f, 0x69, 0x6e, 0x2f, 0x62, 0x61, 0x6c, 0x61,
	0x6e, 0x63, 0x65, 0x2f, 0x7b, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x7d, 0x42, 0x2e, 0x0a,
	0x0b, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x1d,
	0x65, 0x63, 0x6f, 0x6e, 0x6f, 0x6d, 0x79, 0x5f, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x63, 0x6f, 0x69, 0x6e, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_coin_v1_coin_proto_rawDescOnce sync.Once
	file_api_coin_v1_coin_proto_rawDescData = file_api_coin_v1_coin_proto_rawDesc
)

func file_api_coin_v1_coin_proto_rawDescGZIP() []byte {
	file_api_coin_v1_coin_proto_rawDescOnce.Do(func() {
		file_api_coin_v1_coin_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_coin_v1_coin_proto_rawDescData)
	})
	return file_api_coin_v1_coin_proto_rawDescData
}

var file_api_coin_v1_coin_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_coin_v1_coin_proto_goTypes = []interface{}{
	(*RechargeCoinRequest)(nil),   // 0: api.coin.v1.RechargeCoinRequest
	(*RechargeCoinReply)(nil),     // 1: api.coin.v1.RechargeCoinReply
	(*ConsumeCoinRequest)(nil),    // 2: api.coin.v1.ConsumeCoinRequest
	(*ConsumeCoinReply)(nil),      // 3: api.coin.v1.ConsumeCoinReply
	(*GetCoinBalanceRequest)(nil), // 4: api.coin.v1.GetCoinBalanceRequest
	(*GetCoinBalanceReply)(nil),   // 5: api.coin.v1.GetCoinBalanceReply
}
var file_api_coin_v1_coin_proto_depIdxs = []int32{
	0, // 0: api.coin.v1.Coin.Recharge:input_type -> api.coin.v1.RechargeCoinRequest
	2, // 1: api.coin.v1.Coin.ConsumeCoin:input_type -> api.coin.v1.ConsumeCoinRequest
	4, // 2: api.coin.v1.Coin.GetCoinBalance:input_type -> api.coin.v1.GetCoinBalanceRequest
	1, // 3: api.coin.v1.Coin.Recharge:output_type -> api.coin.v1.RechargeCoinReply
	3, // 4: api.coin.v1.Coin.ConsumeCoin:output_type -> api.coin.v1.ConsumeCoinReply
	5, // 5: api.coin.v1.Coin.GetCoinBalance:output_type -> api.coin.v1.GetCoinBalanceReply
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_coin_v1_coin_proto_init() }
func file_api_coin_v1_coin_proto_init() {
	if File_api_coin_v1_coin_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_coin_v1_coin_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RechargeCoinRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_coin_v1_coin_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RechargeCoinReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_coin_v1_coin_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConsumeCoinRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_coin_v1_coin_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConsumeCoinReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_coin_v1_coin_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCoinBalanceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_coin_v1_coin_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCoinBalanceReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_coin_v1_coin_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_coin_v1_coin_proto_goTypes,
		DependencyIndexes: file_api_coin_v1_coin_proto_depIdxs,
		MessageInfos:      file_api_coin_v1_coin_proto_msgTypes,
	}.Build()
	File_api_coin_v1_coin_proto = out.File
	file_api_coin_v1_coin_proto_rawDesc = nil
	file_api_coin_v1_coin_proto_goTypes = nil
	file_api_coin_v1_coin_proto_depIdxs = nil
}
