server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
  kafka:
    addr: 127.0.0.1:9092
    topic: gift_bill
    group: gift_group
    version: 2.1.1
    oldest: false
    assignor: roundrobin
    topics: gift_bill
data:
  database:
    driver: mysql
    source: root:Urie_308@tcp(127.0.0.1:3306)/economy_system?charset=utf8&parseTime=true
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
client:
  grpc:
    addr: 127.0.0.1:9000
    timeout: 1s
  kafka:
    addr: 127.0.0.1:9092
    topic: gift_bill,gift_req
